name: Matrix OS / Python Version - Run Tests & Build Docs

on:
  push:
    branches:
      - '*'
#  pull_request:
#    branches:
#      - '*'

jobs:
  example-1:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Conda
        uses: s-weigand/setup-conda@v1
        with:
          activate-conda: false

      - name: Install Env
        shell: bash
        run: |
          conda env create -f ci/environment.yml

      - name: Check Environment
        shell: bash
        run: |
          source activate earthpy-dev
          conda list
          python -v
      - name: Run Tests
        shell: bash
        run: |
          source activate earthpy-dev
          pytest -v --color=yes
          conda list
          which python
#    steps:
#      - uses: conda-incubator/setup-miniconda@v2
#        with:
#          auto-update-conda: true
#          activate-environment: anaconda-client-env
#          environment-file: ci/environment.yml
#          python-version: ${{ matrix.python-version }}
#          channels: conda-forge
#      - name: Conda info
#        shell: bash -l {0}
#        run: conda info