name: Run Tests & Build Docs - Matrix OS / Python Version

on:
  push:
    branches:
      - '*'
#  pull_request:
#    branches:
#      - '*'

jobs:
  example-1:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"] #["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: [3.7] #[3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Conda
        uses: s-weigand/setup-conda@v1
        with:
          activate-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Install Env
        shell: bash
        run: |
          python --version
          #conda env create -f ci/environment.yml
          conda install -c  conda-forge matplotlib pytest requests  \
            geopandas rasterio scikit-image

      - name: Check Environment
        shell: bash
        run: |
          conda list
          python --version
      - name: Run Tests
        shell: bash
        run: |
          pytest -v --color=yes
          python --version