name: Matrix OS / Python Version - Run Tests & Build Docs

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  example-1:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: [3.7, 3.8]
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: anaconda-client-env
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
      - name: Conda info
        shell: bash -l {0}
        run: conda info